
# DO NOT EDIT THIS AUTOGENERATED FILE!
def _load_consts(t):
    r"""__NATIVE__
    pPmTuple_t ptup;
    pPmObj_t pobj;
    PmReturn_t retval;
    int16_t i;

    // we can't handle exceptions yet, so use assertions to
    // stop the interpreter in case of error.

    C_ASSERT(NATIVE_GET_NUM_ARGS() == 1);

    ptup = (pPmTuple_t) NATIVE_GET_LOCAL(0);
    C_ASSERT(NUM_CONSTANTS == tuple_getLength(ptup));
    
    for (i=0; i<NUM_CONSTANTS; i++) {
        retval = tuple_getItem(ptup, i, &pobj);
        C_ASSERT(retval == PM_RET_OK);

        gVmGlobal.consts[i] = pobj;
    }

    NATIVE_SET_TOS(PM_TRUE);
    return retval;
    """
    pass


_load_consts(('_list', '_dict', '_str', '_set', '_thd', '_tuple', '_Autobox', 'obj', 'code', '__init__', '__str__', 'Generator', 'next', 'Exception', 'None', 'False', 'True', '__bi', 'Any'))
